# Site settings
title: 
header-img: img/home-bg.png
email: monica.l.seaman@gmail.com
copyright_name: mseaman6
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mseaman6
learn_profile: mseaman6
email_username: monica.l.seaman@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
